# Generated by Django 3.2.4 on 2021-07-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('origen', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoMedidor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origen', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=40)),
                ('parroquia', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='administrativo.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='administrativo.marcamedidor')),
            ],
        ),
    ]
